### ISSUE TITLE
메인 이미지 교체, home 수정

### ISSUE THREAD

**Issue by leedo97y** [leedo97y/planteven#7]
### TODO

- [x] 메인 식물 이미지 교체
- [x] home 색상 수정
- [ ] theme 색상 수정
- [x] 글씨체 수정
