### ISSUE TITLE
detail page 디자인 수정, memoSection 추가

### ISSUE THREAD

**Issue by leedo97y** [leedo97y/planteven#9]
### TODO

- [x] memoSection 추가
- [x] label 코드 수정
- [x] label 스타일 수정
- [x] theme 색상 추가 및 수정
- [x] detail 세부 text 수정
- [x] 전체 UI 수정
- [x] font 수정
